version: 1.0.{build}
branches:
  only:
  - master
  - /.*-criteo.*/
image: Visual Studio 2017
init:
- git config --global core.autocrlf true
configuration:
- Release
environment:
  image_flag: 2017
build_script: build.cmd -configuration Release 
artifacts:
- path: '**\*.nupkg'
